# Generated by Django 5.2.7 on 2026-01-26 03:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('money_owned', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='MarketSightBack.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_choice', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('price_bought', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to='MarketSightBack.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('book_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to='MarketSightBack.portfolio')),
            ],
        ),
    ]
