# Generated by Django 5.1.7 on 2025-04-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketSightBack', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='code',
            new_name='symbol',
        ),
    ]
