# Generated by Django 5.1.7 on 2025-04-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketSightBack', '0003_rename_code_stock_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
