# Generated by Django 5.1.7 on 2025-04-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketSightBack', '0004_delete_stock_remove_room_users_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
