# Generated by Django 5.0.2 on 2025-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketSightBack', '0007_message_portfolio_profile_transaction_delete_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='money_owned',
            field=models.IntegerField(default=100000),
        ),
    ]
