# Generated by Django 5.2.7 on 2026-01-05 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketSightBack', '0009_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='ticker',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='MarketSightBack.profile'),
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_choice', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('price_bought', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to='MarketSightBack.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('book_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to='MarketSightBack.portfolio')),
            ],
        ),
    ]
